# Generated by Django 5.1.6 on 2025-09-17 07:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("module_id", models.CharField(default="CC", max_length=20)),
                ("content_id", models.CharField(default="response", max_length=40)),
                ("triggers", models.JSONField(blank=True, null=True)),
                ("queries", models.CharField(blank=True, max_length=800, null=True)),
                ("responses", models.CharField(max_length=800)),
                ("source_version", models.IntegerField(default=0)),
                ("priority", models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name="HiveConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="default", max_length=80, unique=True),
                ),
                (
                    "openai_api_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("google_api_key", models.TextField(blank=True, null=True)),
                (
                    "external_host",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("allow_unverified_bots", models.BooleanField(default=False)),
                ("common_config", models.JSONField(blank=True, null=True)),
                ("common_settings", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MoxieSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("schedule", models.JSONField()),
                ("source_version", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(default=uuid.uuid4, max_length=64, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
            },
        ),
        migrations.CreateModel(
            name="MoxieDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=200, unique=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("robot_settings", models.JSONField(blank=True, null=True)),
                ("robot_config", models.JSONField(blank=True, null=True)),
                ("first_connect", models.DateTimeField(auto_now_add=True)),
                ("last_connect", models.DateTimeField(blank=True, null=True)),
                ("last_disconnect", models.DateTimeField(blank=True, null=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hive.moxieschedule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersistentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(blank=True, null=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hive.moxiedevice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SinglePromptChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_id", models.CharField(max_length=40)),
                ("content_id", models.CharField(max_length=40)),
                ("name", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "debug_instructions",
                    models.CharField(blank=True, max_length=800, null=True),
                ),
                ("prompt", models.TextField(blank=True, null=True)),
                ("initial_npc", models.TextField(blank=True, null=True)),
                ("source_version", models.IntegerField(default=0)),
            ],
            options={
                "unique_together": {("module_id", "content_id")},
            },
        ),
        migrations.CreateModel(
            name="MentorBehavior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_id", models.CharField(blank=True, max_length=80, null=True)),
                ("content_id", models.CharField(blank=True, max_length=80, null=True)),
                ("content_day", models.CharField(blank=True, max_length=80, null=True)),
                ("timestamp", models.BigIntegerField()),
                ("action", models.CharField(blank=True, max_length=80, null=True)),
                ("instance_id", models.BigIntegerField()),
                (
                    "ended_reason",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hive.moxiedevice",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"], name="device_timestamp_idx"
                    )
                ],
            },
        ),
    ]
