# Generated by Django 5.1.6 on 2025-08-07 20:00

import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('pattern', models.TextField()),
                ('entity_groups', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('action', models.IntegerField(choices=[(1, 'RESPONSE'), (2, 'LAUNCH'), (3, 'CONFIRM_LAUNCH'), (4, 'METHOD')], default=1)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('response_markup', models.TextField(blank=True, null=True)),
                ('module_id', models.CharField(blank=True, max_length=80, null=True)),
                ('content_id', models.CharField(blank=True, max_length=80, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('sort_key', models.IntegerField(default=1)),
                ('source_version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='HiveConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('openai_api_key', models.TextField(blank=True, default='', null=True)),
                ('external_host', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('allow_unverified_bots', models.BooleanField(default=False)),
                ('google_api_key', models.TextField(blank=True, default='', null=True)),
                ('common_config', models.JSONField(blank=True, null=True)),
                ('common_settings', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoxieDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('permit', models.IntegerField(choices=[(1, 'UNKNOWN'), (2, 'PENDING'), (3, 'ALLOWED')], default=1)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_connect', models.DateTimeField(blank=True, null=True)),
                ('last_disconnect', models.DateTimeField(blank=True, null=True)),
                ('state', models.JSONField(blank=True, null=True)),
                ('state_updated', models.DateTimeField(blank=True, null=True)),
                ('robot_config', models.JSONField(blank=True, null=True)),
                ('robot_settings', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoxieSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('schedule', models.JSONField()),
                ('source_version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SinglePromptChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('module_id', models.CharField(max_length=200)),
                ('content_id', models.CharField(max_length=200)),
                ('max_history', models.IntegerField(default=20)),
                ('max_volleys', models.IntegerField(default=9999)),
                ('opener', models.TextField()),
                ('prompt', models.TextField()),
                ('vendor', models.IntegerField(choices=[(1, 'OPEN_AI')], default=1)),
                ('model', models.CharField(default='gpt-3.5-turbo', max_length=200)),
                ('max_tokens', models.IntegerField(default=70)),
                ('temperature', models.FloatField(default=0.5)),
                ('code', models.TextField(blank=True, null=True)),
                ('source_version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MoxieLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField()),
                ('uid', models.IntegerField()),
                ('tag', models.CharField(max_length=80)),
                ('message', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hive.moxiedevice')),
            ],
        ),
        migrations.AddField(
            model_name='moxiedevice',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hive.moxieschedule'),
        ),
        migrations.CreateModel(
            name='PersistentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hive.moxiedevice')),
            ],
        ),
        migrations.CreateModel(
            name='MentorBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(blank=True, max_length=80, null=True)),
                ('content_id', models.CharField(blank=True, max_length=80, null=True)),
                ('content_day', models.CharField(blank=True, max_length=80, null=True)),
                ('timestamp', models.BigIntegerField()),
                ('action', models.CharField(blank=True, max_length=80, null=True)),
                ('instance_id', models.BigIntegerField()),
                ('ended_reason', models.CharField(blank=True, max_length=80, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hive.moxiedevice')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'timestamp'], name='device_timestamp_idx')],
            },
        ),
    ]
