# Generated by Django 4.2.24 on 2025-09-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalresponse',
            name='action',
            field=models.IntegerField(choices=[(1, 'RESPONSE'), (2, 'LAUNCH'), (3, 'CONFIRM_LAUNCH'), (4, 'METHOD')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='globalresponse',
            name='name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='hiveconfiguration',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='moxiedevice',
            name='device_id',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='moxiedevice',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='moxiedevice',
            name='permit',
            field=models.IntegerField(choices=[(1, 'UNKNOWN'), (2, 'PENDING'), (3, 'ALLOWED')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='moxielogs',
            name='tag',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='moxielogs',
            name='timestamp',
            field=models.TimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='moxielogs',
            index=models.Index(fields=['device', 'timestamp'], name='logs_device_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='moxielogs',
            index=models.Index(fields=['device', 'tag'], name='logs_device_tag_idx'),
        ),
    ]
