# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cloudtts.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63loudtts.proto\x12\x0e\x65mbodied.unity\"P\n\x07TTSMark\x12\x0c\n\x04time\x18\x01 \x01(\r\x12\r\n\x05start\x18\x02 \x01(\r\x12\x0b\n\x03\x65nd\x18\x03 \x01(\r\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\r\n\x05value\x18\x05 \x01(\t\"\x99\x01\n\x0f\x43loudTTSRequest\x12\x0e\n\x06markup\x18\x01 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\t\x12\x11\n\tchunk_num\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\x12\x0f\n\x07user_id\x18\x05 \x01(\t\x12\x18\n\x10software_version\x18\x64 \x01(\t\x12\x13\n\x0bmodule_name\x18\x65 \x01(\t\"D\n\x0b\x41udioBuffer\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\x12\x10\n\x08\x63hannels\x18\x02 \x01(\x05\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x05\"\xb4\x02\n\x10\x43loudTTSResponse\x12\x39\n\x0erequest_source\x18\x01 \x01(\x0e\x32!.embodied.unity.RequestSourceType\x12*\n\x05\x61udio\x18\x02 \x01(\x0b\x32\x1b.embodied.unity.AudioBuffer\x12&\n\x05marks\x18\x03 \x03(\x0b\x32\x17.embodied.unity.TTSMark\x12\x10\n\x08\x65vent_id\x18\x04 \x01(\t\x12\x11\n\tchunk_num\x18\x05 \x01(\x05\x12\x11\n\ttimestamp\x18\x06 \x01(\x04\x12\x12\n\ntotal_time\x18\x07 \x01(\x04\x12\x16\n\x0esynthesis_time\x18\x08 \x01(\x04\x12\x18\n\x10software_version\x18\x64 \x01(\t\x12\x13\n\x0bmodule_name\x18\x65 \x01(\t\"\x8c\x02\n\x12\x43loudTTSSupplement\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\t\x12\x11\n\tchunk_num\x18\x03 \x01(\x05\x12\x0c\n\x04text\x18\x04 \x01(\t\x12\x0e\n\x06markup\x18\x05 \x01(\t\x12\x18\n\x10translation_time\x18\x06 \x01(\x04\x12\x17\n\x0f\x61utomarkup_time\x18\x07 \x01(\x04\x12\x16\n\x0esynthesis_time\x18\x08 \x01(\x04\x12\x12\n\ntts_engine\x18\t \x01(\t\x12\x12\n\ntotal_time\x18\x14 \x01(\x04\x12\x18\n\x10software_version\x18\x64 \x01(\t\x12\x13\n\x0bmodule_name\x18\x65 \x01(\t*F\n\x11RequestSourceType\x12\x15\n\x11ROBOT_TTS_REQUEST\x10\x00\x12\x1a\n\x16REMOTECHAT_TTS_REQUEST\x10\x01\x62\x06proto3')

_REQUESTSOURCETYPE = DESCRIPTOR.enum_types_by_name['RequestSourceType']
RequestSourceType = enum_type_wrapper.EnumTypeWrapper(_REQUESTSOURCETYPE)
ROBOT_TTS_REQUEST = 0
REMOTECHAT_TTS_REQUEST = 1


_TTSMARK = DESCRIPTOR.message_types_by_name['TTSMark']
_CLOUDTTSREQUEST = DESCRIPTOR.message_types_by_name['CloudTTSRequest']
_AUDIOBUFFER = DESCRIPTOR.message_types_by_name['AudioBuffer']
_CLOUDTTSRESPONSE = DESCRIPTOR.message_types_by_name['CloudTTSResponse']
_CLOUDTTSSUPPLEMENT = DESCRIPTOR.message_types_by_name['CloudTTSSupplement']
TTSMark = _reflection.GeneratedProtocolMessageType('TTSMark', (_message.Message,), {
  'DESCRIPTOR' : _TTSMARK,
  '__module__' : 'cloudtts_pb2'
  # @@protoc_insertion_point(class_scope:embodied.unity.TTSMark)
  })
_sym_db.RegisterMessage(TTSMark)

CloudTTSRequest = _reflection.GeneratedProtocolMessageType('CloudTTSRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLOUDTTSREQUEST,
  '__module__' : 'cloudtts_pb2'
  # @@protoc_insertion_point(class_scope:embodied.unity.CloudTTSRequest)
  })
_sym_db.RegisterMessage(CloudTTSRequest)

AudioBuffer = _reflection.GeneratedProtocolMessageType('AudioBuffer', (_message.Message,), {
  'DESCRIPTOR' : _AUDIOBUFFER,
  '__module__' : 'cloudtts_pb2'
  # @@protoc_insertion_point(class_scope:embodied.unity.AudioBuffer)
  })
_sym_db.RegisterMessage(AudioBuffer)

CloudTTSResponse = _reflection.GeneratedProtocolMessageType('CloudTTSResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLOUDTTSRESPONSE,
  '__module__' : 'cloudtts_pb2'
  # @@protoc_insertion_point(class_scope:embodied.unity.CloudTTSResponse)
  })
_sym_db.RegisterMessage(CloudTTSResponse)

CloudTTSSupplement = _reflection.GeneratedProtocolMessageType('CloudTTSSupplement', (_message.Message,), {
  'DESCRIPTOR' : _CLOUDTTSSUPPLEMENT,
  '__module__' : 'cloudtts_pb2'
  # @@protoc_insertion_point(class_scope:embodied.unity.CloudTTSSupplement)
  })
_sym_db.RegisterMessage(CloudTTSSupplement)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTSOURCETYPE._serialized_start=924
  _REQUESTSOURCETYPE._serialized_end=994
  _TTSMARK._serialized_start=34
  _TTSMARK._serialized_end=114
  _CLOUDTTSREQUEST._serialized_start=117
  _CLOUDTTSREQUEST._serialized_end=270
  _AUDIOBUFFER._serialized_start=272
  _AUDIOBUFFER._serialized_end=340
  _CLOUDTTSRESPONSE._serialized_start=343
  _CLOUDTTSRESPONSE._serialized_end=651
  _CLOUDTTSSUPPLEMENT._serialized_start=654
  _CLOUDTTSSUPPLEMENT._serialized_end=922
# @@protoc_insertion_point(module_scope)
