# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloudtts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloudtts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63loudtts.proto\x12\x0e\x65mbodied.unity\"P\n\x07TTSMark\x12\x0c\n\x04time\x18\x01 \x01(\r\x12\r\n\x05start\x18\x02 \x01(\r\x12\x0b\n\x03\x65nd\x18\x03 \x01(\r\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\r\n\x05value\x18\x05 \x01(\t\"\x99\x01\n\x0f\x43loudTTSRequest\x12\x0e\n\x06markup\x18\x01 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\t\x12\x11\n\tchunk_num\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\x12\x0f\n\x07user_id\x18\x05 \x01(\t\x12\x18\n\x10software_version\x18\x64 \x01(\t\x12\x13\n\x0bmodule_name\x18\x65 \x01(\t\"D\n\x0b\x41udioBuffer\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\x12\x10\n\x08\x63hannels\x18\x02 \x01(\x05\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x05\"\xb4\x02\n\x10\x43loudTTSResponse\x12\x39\n\x0erequest_source\x18\x01 \x01(\x0e\x32!.embodied.unity.RequestSourceType\x12*\n\x05\x61udio\x18\x02 \x01(\x0b\x32\x1b.embodied.unity.AudioBuffer\x12&\n\x05marks\x18\x03 \x03(\x0b\x32\x17.embodied.unity.TTSMark\x12\x10\n\x08\x65vent_id\x18\x04 \x01(\t\x12\x11\n\tchunk_num\x18\x05 \x01(\x05\x12\x11\n\ttimestamp\x18\x06 \x01(\x04\x12\x12\n\ntotal_time\x18\x07 \x01(\x04\x12\x16\n\x0esynthesis_time\x18\x08 \x01(\x04\x12\x18\n\x10software_version\x18\x64 \x01(\t\x12\x13\n\x0bmodule_name\x18\x65 \x01(\t\"\x8c\x02\n\x12\x43loudTTSSupplement\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\t\x12\x11\n\tchunk_num\x18\x03 \x01(\x05\x12\x0c\n\x04text\x18\x04 \x01(\t\x12\x0e\n\x06markup\x18\x05 \x01(\t\x12\x18\n\x10translation_time\x18\x06 \x01(\x04\x12\x17\n\x0f\x61utomarkup_time\x18\x07 \x01(\x04\x12\x16\n\x0esynthesis_time\x18\x08 \x01(\x04\x12\x12\n\ntts_engine\x18\t \x01(\t\x12\x12\n\ntotal_time\x18\x14 \x01(\x04\x12\x18\n\x10software_version\x18\x64 \x01(\t\x12\x13\n\x0bmodule_name\x18\x65 \x01(\t*F\n\x11RequestSourceType\x12\x15\n\x11ROBOT_TTS_REQUEST\x10\x00\x12\x1a\n\x16REMOTECHAT_TTS_REQUEST\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloudtts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTSOURCETYPE']._serialized_start=924
  _globals['_REQUESTSOURCETYPE']._serialized_end=994
  _globals['_TTSMARK']._serialized_start=34
  _globals['_TTSMARK']._serialized_end=114
  _globals['_CLOUDTTSREQUEST']._serialized_start=117
  _globals['_CLOUDTTSREQUEST']._serialized_end=270
  _globals['_AUDIOBUFFER']._serialized_start=272
  _globals['_AUDIOBUFFER']._serialized_end=340
  _globals['_CLOUDTTSRESPONSE']._serialized_start=343
  _globals['_CLOUDTTSRESPONSE']._serialized_end=651
  _globals['_CLOUDTTSSUPPLEMENT']._serialized_start=654
  _globals['_CLOUDTTSSUPPLEMENT']._serialized_end=922
# @@protoc_insertion_point(module_scope)
